// Copyright 2021-2022, University of Colorado Boulder

/**
 * Auto-generated from modulify, DO NOT manually modify.
 */
/* eslint-disable */
import getStringModule from '../../chipper/js/getStringModule.js';
import TReadOnlyProperty from '../../axon/js/TReadOnlyProperty.js';
import circuitConstructionKitCommon from './circuitConstructionKitCommon.js';

type StringsType = {
  'circuit-construction-kit-common': {
    'title': string;
    'titleStringProperty': TReadOnlyProperty<string>;
  };
  'schematicStandard': string;
  'schematicStandardStringProperty': TReadOnlyProperty<string>;
  'realBulb': string;
  'realBulbStringProperty': TReadOnlyProperty<string>;
  'ieee': string;
  'ieeeStringProperty': TReadOnlyProperty<string>;
  'iec': string;
  'iecStringProperty': TReadOnlyProperty<string>;
  'british': string;
  'britishStringProperty': TReadOnlyProperty<string>;
  'animationSpeedLimitReached': string;
  'animationSpeedLimitReachedStringProperty': TReadOnlyProperty<string>;
  'acSource': string;
  'acSourceStringProperty': TReadOnlyProperty<string>;
  'advanced': string;
  'advancedStringProperty': TReadOnlyProperty<string>;
  'resistor': string;
  'resistorStringProperty': TReadOnlyProperty<string>;
  'capacitor': string;
  'capacitorStringProperty': TReadOnlyProperty<string>;
  'inductor': string;
  'inductorStringProperty': TReadOnlyProperty<string>;
  'stopwatch': string;
  'stopwatchStringProperty': TReadOnlyProperty<string>;
  'fuse': string;
  'fuseStringProperty': TReadOnlyProperty<string>;
  'time': string;
  'timeStringProperty': TReadOnlyProperty<string>;
  'oneSecond': string;
  'oneSecondStringProperty': TReadOnlyProperty<string>;
  'capacitance': string;
  'capacitanceStringProperty': TReadOnlyProperty<string>;
  'inductance': string;
  'inductanceStringProperty': TReadOnlyProperty<string>;
  'currentRating': string;
  'currentRatingStringProperty': TReadOnlyProperty<string>;
  'tiny': string;
  'tinyStringProperty': TReadOnlyProperty<string>;
  'lots': string;
  'lotsStringProperty': TReadOnlyProperty<string>;
  'phaseShift': string;
  'phaseShiftStringProperty': TReadOnlyProperty<string>;
  'coin': string;
  'coinStringProperty': TReadOnlyProperty<string>;
  'dollarBill': string;
  'dollarBillStringProperty': TReadOnlyProperty<string>;
  'eraser': string;
  'eraserStringProperty': TReadOnlyProperty<string>;
  'pencil': string;
  'pencilStringProperty': TReadOnlyProperty<string>;
  'hand': string;
  'handStringProperty': TReadOnlyProperty<string>;
  'dog': string;
  'dogStringProperty': TReadOnlyProperty<string>;
  'paperClip': string;
  'paperClipStringProperty': TReadOnlyProperty<string>;
  'wireResistivity': string;
  'wireResistivityStringProperty': TReadOnlyProperty<string>;
  'batteryResistance': string;
  'batteryResistanceStringProperty': TReadOnlyProperty<string>;
  'sourceResistance': string;
  'sourceResistanceStringProperty': TReadOnlyProperty<string>;
  'battery': string;
  'batteryStringProperty': TReadOnlyProperty<string>;
  'lightBulb': string;
  'lightBulbStringProperty': TReadOnlyProperty<string>;
  'addRealBulbs': string;
  'addRealBulbsStringProperty': TReadOnlyProperty<string>;
  'switch': string;
  'switchStringProperty': TReadOnlyProperty<string>;
  'wire': string;
  'wireStringProperty': TReadOnlyProperty<string>;
  'electrons': string;
  'electronsStringProperty': TReadOnlyProperty<string>;
  'conventional': string;
  'conventionalStringProperty': TReadOnlyProperty<string>;
  'tapCircuitElementToEdit': string;
  'tapCircuitElementToEditStringProperty': TReadOnlyProperty<string>;
  'current': string;
  'currentStringProperty': TReadOnlyProperty<string>;
  'showCurrent': string;
  'showCurrentStringProperty': TReadOnlyProperty<string>;
  'resistance': string;
  'resistanceStringProperty': TReadOnlyProperty<string>;
  'voltage': string;
  'voltageStringProperty': TReadOnlyProperty<string>;
  'voltageWithUnits': string;
  'voltageWithUnitsStringProperty': TReadOnlyProperty<string>;
  'voltageChart': string;
  'voltageChartStringProperty': TReadOnlyProperty<string>;
  'currentWithUnits': string;
  'currentWithUnitsStringProperty': TReadOnlyProperty<string>;
  'currentChart': string;
  'currentChartStringProperty': TReadOnlyProperty<string>;
  'frequency': string;
  'frequencyStringProperty': TReadOnlyProperty<string>;
  'voltmeter': string;
  'voltmeterStringProperty': TReadOnlyProperty<string>;
  'ammeter': string;
  'ammeterStringProperty': TReadOnlyProperty<string>;
  'ammeters': string;
  'ammetersStringProperty': TReadOnlyProperty<string>;
  'labels': string;
  'labelsStringProperty': TReadOnlyProperty<string>;
  'values': string;
  'valuesStringProperty': TReadOnlyProperty<string>;
  'ohms': string;
  'ohmsStringProperty': TReadOnlyProperty<string>;
  'voltageUnits': string;
  'voltageUnitsStringProperty': TReadOnlyProperty<string>;
  'voltageVoltsValuePattern': string;
  'voltageVoltsValuePatternStringProperty': TReadOnlyProperty<string>;
  'frequencyHzValuePattern': string;
  'frequencyHzValuePatternStringProperty': TReadOnlyProperty<string>;
  'currentUnits': string;
  'currentUnitsStringProperty': TReadOnlyProperty<string>;
  'capacitanceUnits': string;
  'capacitanceUnitsStringProperty': TReadOnlyProperty<string>;
  'inductanceUnits': string;
  'inductanceUnitsStringProperty': TReadOnlyProperty<string>;
  'fuseValue': string;
  'fuseValueStringProperty': TReadOnlyProperty<string>;
  'resistanceOhmsSymbol': string;
  'resistanceOhmsSymbolStringProperty': TReadOnlyProperty<string>;
  'capacitanceFaradsSymbol': string;
  'capacitanceFaradsSymbolStringProperty': TReadOnlyProperty<string>;
  'inductanceHenriesSymbol': string;
  'inductanceHenriesSymbolStringProperty': TReadOnlyProperty<string>;
  'resistanceOhmsValuePattern': string;
  'resistanceOhmsValuePatternStringProperty': TReadOnlyProperty<string>;
  'theSwitchIsClosed': string;
  'theSwitchIsClosedStringProperty': TReadOnlyProperty<string>;
  'theSwitchIsOpen': string;
  'theSwitchIsOpenStringProperty': TReadOnlyProperty<string>;
  'ammeterReadout': string;
  'ammeterReadoutStringProperty': TReadOnlyProperty<string>;
  'magnitude': string;
  'magnitudeStringProperty': TReadOnlyProperty<string>;
  'signed': string;
  'signedStringProperty': TReadOnlyProperty<string>;
  'dataOutOfRange': string;
  'dataOutOfRangeStringProperty': TReadOnlyProperty<string>;
};

const CircuitConstructionKitCommonStrings = getStringModule( 'CIRCUIT_CONSTRUCTION_KIT_COMMON' ) as StringsType;

circuitConstructionKitCommon.register( 'CircuitConstructionKitCommonStrings', CircuitConstructionKitCommonStrings );

export default CircuitConstructionKitCommonStrings;
