// Copyright 2021-2022, University of Colorado Boulder

/**
 * Auto-generated from modulify, DO NOT manually modify.
 */
/* eslint-disable */
import getStringModule from '../../chipper/js/getStringModule.js';
import LinkableProperty from '../../axon/js/LinkableProperty.js';
import circuitConstructionKitCommon from './circuitConstructionKitCommon.js';

type StringsType = {
  'circuit-construction-kit-common': {
    'title': string;
    'titleStringProperty': LinkableProperty<string>;
  };
  'schematicStandard': string;
  'schematicStandardStringProperty': LinkableProperty<string>;
  'realBulb': string;
  'realBulbStringProperty': LinkableProperty<string>;
  'ieee': string;
  'ieeeStringProperty': LinkableProperty<string>;
  'iec': string;
  'iecStringProperty': LinkableProperty<string>;
  'british': string;
  'britishStringProperty': LinkableProperty<string>;
  'animationSpeedLimitReached': string;
  'animationSpeedLimitReachedStringProperty': LinkableProperty<string>;
  'acSource': string;
  'acSourceStringProperty': LinkableProperty<string>;
  'advanced': string;
  'advancedStringProperty': LinkableProperty<string>;
  'resistor': string;
  'resistorStringProperty': LinkableProperty<string>;
  'capacitor': string;
  'capacitorStringProperty': LinkableProperty<string>;
  'inductor': string;
  'inductorStringProperty': LinkableProperty<string>;
  'stopwatch': string;
  'stopwatchStringProperty': LinkableProperty<string>;
  'fuse': string;
  'fuseStringProperty': LinkableProperty<string>;
  'time': string;
  'timeStringProperty': LinkableProperty<string>;
  'oneSecond': string;
  'oneSecondStringProperty': LinkableProperty<string>;
  'capacitance': string;
  'capacitanceStringProperty': LinkableProperty<string>;
  'inductance': string;
  'inductanceStringProperty': LinkableProperty<string>;
  'currentRating': string;
  'currentRatingStringProperty': LinkableProperty<string>;
  'tiny': string;
  'tinyStringProperty': LinkableProperty<string>;
  'lots': string;
  'lotsStringProperty': LinkableProperty<string>;
  'phaseShift': string;
  'phaseShiftStringProperty': LinkableProperty<string>;
  'coin': string;
  'coinStringProperty': LinkableProperty<string>;
  'dollarBill': string;
  'dollarBillStringProperty': LinkableProperty<string>;
  'eraser': string;
  'eraserStringProperty': LinkableProperty<string>;
  'pencil': string;
  'pencilStringProperty': LinkableProperty<string>;
  'hand': string;
  'handStringProperty': LinkableProperty<string>;
  'dog': string;
  'dogStringProperty': LinkableProperty<string>;
  'paperClip': string;
  'paperClipStringProperty': LinkableProperty<string>;
  'wireResistivity': string;
  'wireResistivityStringProperty': LinkableProperty<string>;
  'batteryResistance': string;
  'batteryResistanceStringProperty': LinkableProperty<string>;
  'sourceResistance': string;
  'sourceResistanceStringProperty': LinkableProperty<string>;
  'battery': string;
  'batteryStringProperty': LinkableProperty<string>;
  'lightBulb': string;
  'lightBulbStringProperty': LinkableProperty<string>;
  'addRealBulbs': string;
  'addRealBulbsStringProperty': LinkableProperty<string>;
  'switch': string;
  'switchStringProperty': LinkableProperty<string>;
  'wire': string;
  'wireStringProperty': LinkableProperty<string>;
  'electrons': string;
  'electronsStringProperty': LinkableProperty<string>;
  'conventional': string;
  'conventionalStringProperty': LinkableProperty<string>;
  'tapCircuitElementToEdit': string;
  'tapCircuitElementToEditStringProperty': LinkableProperty<string>;
  'current': string;
  'currentStringProperty': LinkableProperty<string>;
  'showCurrent': string;
  'showCurrentStringProperty': LinkableProperty<string>;
  'resistance': string;
  'resistanceStringProperty': LinkableProperty<string>;
  'voltage': string;
  'voltageStringProperty': LinkableProperty<string>;
  'voltageWithUnits': string;
  'voltageWithUnitsStringProperty': LinkableProperty<string>;
  'voltageChart': string;
  'voltageChartStringProperty': LinkableProperty<string>;
  'currentWithUnits': string;
  'currentWithUnitsStringProperty': LinkableProperty<string>;
  'currentChart': string;
  'currentChartStringProperty': LinkableProperty<string>;
  'frequency': string;
  'frequencyStringProperty': LinkableProperty<string>;
  'voltmeter': string;
  'voltmeterStringProperty': LinkableProperty<string>;
  'ammeter': string;
  'ammeterStringProperty': LinkableProperty<string>;
  'ammeters': string;
  'ammetersStringProperty': LinkableProperty<string>;
  'labels': string;
  'labelsStringProperty': LinkableProperty<string>;
  'values': string;
  'valuesStringProperty': LinkableProperty<string>;
  'ohms': string;
  'ohmsStringProperty': LinkableProperty<string>;
  'voltageUnits': string;
  'voltageUnitsStringProperty': LinkableProperty<string>;
  'voltageVoltsValuePattern': string;
  'voltageVoltsValuePatternStringProperty': LinkableProperty<string>;
  'frequencyHzValuePattern': string;
  'frequencyHzValuePatternStringProperty': LinkableProperty<string>;
  'currentUnits': string;
  'currentUnitsStringProperty': LinkableProperty<string>;
  'capacitanceUnits': string;
  'capacitanceUnitsStringProperty': LinkableProperty<string>;
  'inductanceUnits': string;
  'inductanceUnitsStringProperty': LinkableProperty<string>;
  'fuseValue': string;
  'fuseValueStringProperty': LinkableProperty<string>;
  'resistanceOhmsSymbol': string;
  'resistanceOhmsSymbolStringProperty': LinkableProperty<string>;
  'capacitanceFaradsSymbol': string;
  'capacitanceFaradsSymbolStringProperty': LinkableProperty<string>;
  'inductanceHenriesSymbol': string;
  'inductanceHenriesSymbolStringProperty': LinkableProperty<string>;
  'resistanceOhmsValuePattern': string;
  'resistanceOhmsValuePatternStringProperty': LinkableProperty<string>;
  'theSwitchIsClosed': string;
  'theSwitchIsClosedStringProperty': LinkableProperty<string>;
  'theSwitchIsOpen': string;
  'theSwitchIsOpenStringProperty': LinkableProperty<string>;
  'ammeterReadout': string;
  'ammeterReadoutStringProperty': LinkableProperty<string>;
  'magnitude': string;
  'magnitudeStringProperty': LinkableProperty<string>;
  'signed': string;
  'signedStringProperty': LinkableProperty<string>;
  'dataOutOfRange': string;
  'dataOutOfRangeStringProperty': LinkableProperty<string>;
};

const CircuitConstructionKitCommonStrings = getStringModule( 'CIRCUIT_CONSTRUCTION_KIT_COMMON' ) as StringsType;

circuitConstructionKitCommon.register( 'CircuitConstructionKitCommonStrings', CircuitConstructionKitCommonStrings );

export default CircuitConstructionKitCommonStrings;
